### PR TITLE
Update plotly.js to v1.44.3

### PR DESCRIPTION
**Pull request by kozo2**

### CODE REVIEW

**Comment by mrkn** [comment]
@kozo2 I don't know whether this can be merged.

Although the latest CI build on the master branch [succeeded](https://travis-ci.org/ash1day/rbplotly/builds/358318706), the CI build for the commit in this pull-request failed.
At least, could you please fix the failures?

**Comment by kozo2** [comment]
I found that the tests are falling.
I will check what is the problem.

**Comment by kozo2** [comment]
It seems that @ash1day sets Plotly API username and API key in the Travis env vars.
It seems that those values are used only when the upstream repo is updated. (So those are not reflected in my pull-req.)

You do not need to merge this pull-req.
Can you just try updating plotly.js in your repo instead?
It is likely that there is no Travis error (in the case of repo update from there).

**Comment by kozo2** [comment]
Now I found that I can merge this pull-req.
I'll give it a try merging.
If Travis fails, I will revert back

**Comment by kozo2** [comment]
The new Travis build (after the merge) failed like this. I revert this pull-req once.

image

**Pull request merged**
